### ISSUE TITLE
Create Landing/Login Screen

### ISSUE THREAD

**Issue by kmaus** [mikevo/uno-heterogeneous-knowledge#12]

**Comment by mikevo** [comment]
what do you mean with a loading screen?

**Comment by kmaus** [comment]
If we wanted to do a loading page, the sign in information could be apart of it.

**Comment by mikevo** [comment]
what do you mean with the term "loading page"?
do you mean a landing page?

**Comment by kmaus** [comment]
Yep, whoops.

**Comment by mikevo** [comment]
in the first version i'd do landing, sign in and sign up as a seperate view as this should be more strait forward in rails
