### ISSUE TITLE
Assignment/Test Creation/Edit Page

### ISSUE THREAD

**Issue by kmaus** [mikevo/uno-heterogeneous-knowledge#18]
Instructors need a view to create and edit assignments. They should be able to set a due date and assignment name (maybe an assignment type/weight). The user then has the ability to add questions, type the question, add multiple choice options, and select the correct answer(s). Picturing Google Forms-esque.

possible issue on edits would be allowing students who have already completed the assignment to retake it.

**Comment by mikevo** [comment]
If the edit is possible then i would allow students to take the test a second time but choose the better result of both tests for grading. Therefore a student does not suffer from a mistake of a instructor.

**Comment by danieldekerlegand** [comment]
Broken into sub-issue #30

**Comment by kmaus** [comment]
Closed by #30
